version: '3.8'

services:
  db:
    image: mariadb:11.5.2
    restart: always
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3334:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE 
volumes:
  mariadb_data: